- src/apps/relay/mainrelay.c
previously total-quota and user-quota values were mixed up
> fix quota options

- src/apps/relay/mainrelay.c
- src/apps/relay/netengine.c
- src/apps/relay/turn_admin_server.c
- src/apps/relay/turn_admin_server.h
- src/server/ns_turn_server.c
- src/server/ns_turn_server.h
This Pull-Request adds an option, to completely disable the management interface. It's required by some security guidelines.
> Enhancement: Add option to disable Web-Management-Interface

- Dockerfile.build
- build-docker.sh
To build, run ./build-docker.sh.
The outputs will be in the same directory.
Signed-off-by: Hui Kang <kangh@us.ibm.com>
> Build by docker

- postinstall.txt
Fixed typos in postinstall.txt
> fix(doc): Updated copy on postinstall.txt

- Makefile.in
> Minor fixes to Makefile.in

- examples/etc/turnserver.conf
- src/apps/relay/dbdrivers/dbd_mysql.c
- src/apps/relay/mainrelay.c
- src/apps/relay/mainrelay.h
Co-authored-by: Erdem Duman <erdemduman23@gmail.com>
Co-authored-by: mashary <mashar.yazici@gmail.com>
> Adding a encryption logic for the password of MySQL DB user.

- src/apps/relay/dbdrivers/dbd_mysql.c
- src/apps/relay/mainrelay.c
- src/apps/relay/mainrelay.h
"Allow Encoding" Option is deleted.
> Non allow encoding option

- rpm/turnserver.spec
> rpm build fix

- examples/etc/coturn.service
Hello, I added a simple systemd service file example.
How to use it : 
put it in /usr/local/etc/
```
ln -s /usr/local/etc/coturn.service /etc/systemd/system/
systemctl daemon-reload
systemctl enable coturn
systemctl start coturn
systemctl status coturn
```
> Added systemd service file example.

- configure
Hi,
I need to compile Turn Server with private libraries ( Ex : BoringSSL )
This implementation provides to use private libraries for compilation. If user defined X_CFLAGS and X_LIBS variables for private library, "configure" file use this variables. Otherwise works as default.
Added options:
HIREDIS_CFLAGS HIREDIS_LIBS
PSQL_CFLAGS PSQL_LIBS
MYSQL_CFLAGS MYSQL_LIBS
MONGO_CFLAGS MONGO_LIBS
SSL_CFLAGS SSL_LIBS
EVENT_CFLAGS EVENT_LIBS
Thanks for reviewing.
Selahaddin.
> Modifying configure file for enable to compile with private libraries

- docker/coturn/Dockerfile
Hi,
An error occurred in the docker build for coturn.
So I changed the Dockerfile to build succeeds in the latest Debian.
Fix for #426 .
> Fix Dockerfile for latest Debian

- INSTALL
Fix typos about INSTALL filenames.
> Fix typos about INSTALL filenames

- docker/coturn/turnserver.conf
> Change Docker turnserver.conf to latest turnserver.conf

- src/server/ns_turn_server.c
The server->log_binding ptr should be dereferenced
> Fix server->log_binding usage

- src/apps/relay/mainrelay.c
- src/apps/relay/prom_server.c
Other error cases may be added in the future using negative return codes, if necessary.
> Issue #699 Return codes for prom server

- src/apps/relay/dbdrivers/dbd_sqlite.c
Ref https://www.sqlite.org/c3ref/initialize.html:
The sqlite3_initialize() interface is threadsafe, but
sqlite3_shutdown() is not.
We currently call `sqlite3_shutdown` from all threads as part of `sqlite_init_multithreaded`, and this has been observed to have adversarial effects during startup if many threads receive their first inbound request at the same time. The apparent motivation behind calling shutdown is to make the subsequent calls to `sqlite3_config` succeed, since these ordinarily return SQLITE_MISUSE if called multiple times. However, this function is also documented to not be thread safe, so introduce a barrier that ensures we only initialize once over all threads.
> dbd_sqlite: Don't shutdown sqlite3 db during init

- docker/coturn/alpine/Dockerfile
- docker/coturn/debian/Dockerfile
@tyranron @misi hello! Please consider this small change that exposes default TLS ports along with already exposed 3478. Thanks in advance!
> Expose default TLS ports

- examples/etc/turnserver.conf
- src/apps/common/ns_turn_utils.c
- src/apps/common/ns_turn_utils.h
- src/apps/relay/mainrelay.c
With this PR, syslog facility configuration is added.
The user can filter syslog messages by setting the facility.
> Add syslog facility configuration

- src/apps/relay/ns_ioalib_engine_impl.c
Additional properties:
- Socket type
- Local IP address / port
- Remote IP address / port
- SSL type
- SSH cipher
This helps with getting more information on TURN usage and to see where clients are connecting from.
> Include additional properties in redis allocation status reports.

- src/apps/uclient/mainuclient.c
When using `turnutils_uclient` with `-S` flag (TLS or DTLS) it is not required to load certificates. Only load certificates when corresponding flags are provided
Fixes #376 which prevented using `turnutils_uclient` for testing TLS/DTLS connections
Test plan:
- Run local turnserver with certificates `./bin/turnserver --cert ./bin/public.pem --pkey ./bin/private.key --use-auth-secret  --static-auth-secret=secret --realm=north.gov --allow-loopback-peers --no-cli --verbose`
- Run fixed uclient without TLS/DTLS`./bin/turnutils_uclient -e 127.0.0.1 -X -g -u user -W secret 127.0.0.1` and get success result (just to make sure non-secure still works)
- Run fixed uclient with TLS `./bin/turnutils_uclient -e 127.0.0.1 -X -g -u user -W secret -t -S 127.0.0.1` and get success result
- Run fixed …
> Fix uclient certificate loading bug

- debian/changelog
- debian/patches/No-FIPS-140-mode.patch
- debian/patches/series
> Debian changes for 4.5.2-3.1

- src/apps/oauth/oauth.c
- src/apps/relay/userdb.c
Fix a few additional warnings raised by cppcheck
> Fix issues reported by cppcheck

- src/apps/relay/libtelnet.c
- src/apps/relay/libtelnet.h
Split out work on libtelnet from #855 
Required to update libtelnet to introduce compatibility with Windows
This change contains vanilla code of [libtelnet](https://github.com/seanmiddleditch/libtelnet) v0.23 (latest tag)
Test Plan:
- run turnserver locally, set cli password, connect to the turnserver cli interface
- run a few commands - get output
> Update libtelnet to 0.23 (portability issues)

- src/apps/relay/acme.c
- src/apps/relay/dbdrivers/dbd_redis.c
- Unused argument
- Invalid format type when printf-ing size_t
> Fix 2 warnings in code

- src/apps/common/apputils.c
- src/apps/relay/dbdrivers/dbdriver.c
- src/apps/relay/http_server.c
- src/apps/relay/libtelnet.c
- src/apps/relay/userdb.c
- src/apps/uclient/uclient.c
- src/server/ns_turn_maps.c
Clang emitted some easy to fix warnings.
> Fix warnings

- CMakeLists.txt
Re-enable back C11 as was before
> Use c11 standard See: #1055

- src/apps/common/apputils.c
- src/apps/common/ns_turn_utils.c
- src/apps/relay/turn_admin_server.c
- src/client/ns_turn_ioaddr.c
`__APPLE__` is enough to detect macOS
> Simplify defines for macOS platform

- src/server/ns_turn_khash.h
The previously used version of khash trigged some static code analysis warnings that are gone with the latest version:
https://github.com/attractivechaos/klib/blob/9a063b33efd841fcc42d4b9f68cb78bb528bf75b/khash.h
> Use khash 0.2.8

- src/apps/relay/ns_ioalib_engine_impl.c
- src/apps/relay/prom_server.c
- src/apps/relay/prom_server.h
- src/server/ns_turn_ioalib.h
- src/server/ns_turn_server.c
> Add STUN request/response/error prometheus counters

- src/apps/relay/prom_server.c
Hello,
In some cases the prometheus server was started using SELECT even if EPOLL was supported. 
Some flags were changed in microhttpd and now we use MHD_VERSION to make sure to use the right ones in all cases (support old version, for ubuntu 16.04 for ex).
This fixes the issue #1167
I also added a log to make sure we know which version is used, especially to inform the user that the SELECT version might lead to issues on highly used servers.
Thanks,
Thibaut
> Prometheus: make sure microhttpd starts using epoll if supported

- src/apps/common/ns_turn_utils.c
> Change printf() to TURN_LOG_FUNC() for --no-stdout-log

- src/apps/relay/netengine.c
I tested the code part by using manual and automated tools for more than 2 years.
> Fix recursive call in delete alternate server

- vcpkg.json
Please update version in vcpkg.json, when tag
> Update version in vcpkg.json

- src/client/ns_turn_msg.c
follow up to https://github.com/coturn/coturn/pull/1282/files
> strncpy doesn't return size_t

- src/apps/relay/mainrelay.c
- src/apps/relay/ns_ioalib_engine_impl.c
- src/apps/relay/prom_server.c
- src/apps/relay/prom_server.h
TURN_NO_PROMETHEUS define is used in minimal amount of places now
> Reduce ifdefs in code: TURN_NO_PROMETHEUS

- .github/workflows/mingw.yml
- cmake/FindPrometheus.cmake
- configure
- docs/Prometheus.md
- src/apps/relay/CMakeLists.txt
> CMake: find prometheus(fix #1304)

- src/apps/relay/dbdrivers/dbd_sqlite.c
> Fix potential null passed to function expecting nonnull

- src/apps/relay/prom_server.c
#1362 introduced a bug that this PR fixes
> Fix mingw build

- .clang-tidy
- .github/workflows/clang-tidy.yml
- .github/workflows/msvc-analyzer.yml
- iwyu-ubuntu.imp
These code scanners can provide a lot of great automated bug finding capabilities.
> Add clang-tidy, include-what-you-use, and msvc-analyzer github actions

- CMakeLists.txt
> Change minimal required cmake version to 3.16

- src/apps/relay/mainrelay.c
Trivial log warning typo introduced in #1256 corrected.
> Fix no-tls warning typo

- .github/workflows/actions/ubuntu-build-deps/action.yml
- .github/workflows/clang-tidy.yml
- .github/workflows/compiler-sanitizers.yml
- .github/workflows/lint.yml
- .github/workflows/tests.yml
superseding changes made in pr #1394 on request of @jonesmz 
extracted ubuntu build dependencies into a composite action for maintainability reasons
> ubuntu build dependencies extracted to composite actions

- src/apps/relay/mainrelay.c
> Print version only, no extra lines

- CMakeLists.txt
CMake: Declare the variable nearby﻿
> CMake: Declare the variable nearby

- examples/etc/turnserver.conf
> Update turnserver.conf Example about listening-ip

- .github/workflows/macos.yml
- .github/workflows/mingw.yml
- .github/workflows/msvc.yml
pr split on behalf of @jonesmz 
normalisation of some of the workflow files
> workflow tidying

- .github/workflows/macos.yml
- src/apps/relay/mainrelay.c
- src/apps/relay/mainrelay.h
> Add brew upgrade in macos CI

- src/apps/common/apputils.c
- src/apps/common/apputils.h
- src/apps/common/ns_turn_utils.c
- src/apps/natdiscovery/natdiscovery.c
- src/apps/oauth/oauth.c
- src/apps/peer/udpserver.c
- src/apps/relay/dbdrivers/dbd_mongo.c
- src/apps/relay/dbdrivers/dbd_mysql.c
- src/apps/relay/dbdrivers/dbd_redis.c
- src/apps/relay/dtls_listener.c
- src/apps/relay/hiredis_libevent2.c
- src/apps/relay/http_server.c
- src/apps/relay/mainrelay.c
- src/apps/relay/ns_ioalib_engine_impl.c
- src/apps/relay/turn_admin_server.c
- src/server/ns_turn_server.c
- src/server/ns_turn_session.h
Depends on https://github.com/coturn/coturn/pull/1547
> Use calloc where appropriate, avoid memset when normal buffer initialization works

- .github/workflows/lint.yml
- src/apps/relay/mainrelay.c
Reformat to address linter error
> Reformat code

- src/apps/common/stun_buffer.c
- src/apps/common/stun_buffer.h
- src/apps/natdiscovery/natdiscovery.c
- src/apps/oauth/oauth.c
- src/apps/relay/mainrelay.c
- src/apps/relay/turn_admin_server.c
- src/apps/relay/userdb.c
- src/apps/rfc5769/rfc5769check.c
- src/apps/stunclient/stunclient.c
- src/apps/uclient/mainuclient.c
- src/apps/uclient/session.h
- src/apps/uclient/startuclient.c
- src/apps/uclient/uclient.c
- src/client++/TurnMsgLib.h
- src/client/ns_turn_msg.c
- src/client/ns_turn_msg.h
- src/server/ns_turn_server.c
And address knockon effects in other files, e.g. adjust if-statements and other function parameters and return types.
> Use bool, instead of int, for the functions in ns_turn_msg.c

- scripts/install_coturn_on_aws_ec2.sh
https://github.com/coturn/coturn/issues/1576
> Easy installation of coturn on AWS

- AUTHORS.md
- CMakeLists.txt
- ChangeLog
- docker/coturn/Makefile
- examples/scripts/pack.sh
- rpm/build.settings.sh
- rpm/turnserver.spec
- scripts/install_coturn_on_aws_ec2.sh
- src/ns_turn_defs.h
- vcpkg.json
> Update version to 4.6.3

- src/apps/relay/dbdrivers/dbd_redis.c
Fixes a regression pointed out at <https://github.com/coturn/coturn/pull/1488#issuecomment-2801027711>.
A regression was introduced in the last PR where the dbname parameter was not respected if using redis without authentication. The logic for sending the select command responsible for switching to the correct database was wrongly guarded behind authentication being provided. This PR flattens the control flow so the select command is always sent, whether using authentication or not.
> redis: use dbname param when redis is unauthenticated

- src/server/ns_turn_server.c
This commit implements the `send_error_reason` option. When `send_error_reason` is set to `false`, the TURN server will now send an empty reason phrase ("") in STUN error responses. If `send_error_reason` is `true` (the default behavior), the original error reason phrase will be sent.
This change affects how error conditions are communicated to clients, allowing for configurations where detailed error reasons are suppressed.
> feat: implement send_error_reason flag

- src/apps/uclient/startuclient.c
refactored random tri-state to use two random booleans for clarity
> refactored tri-state to bools

- CMakeLists.txt
- configure
- src/client/ns_turn_msg.c
Redoing https://github.com/coturn/coturn/pull/1664 as requested. This adds an optional OAUTH_DISABLED define to allow for disabling OAuth support.
> Add define to disable OAuth support

- src/apps/peer/udpserver.c
Hi,
Fixes resource and memory leaks in `udp_create_server_socket()` by ensuring that the socket file descriptor (`udp_fd`) and dynamically allocated memory (`server_addr`) are properly released on failure.
Specifically, if `addr_bind()`, `event_new()`, or `event_add()` fails, the function now closes the socket and frees memory to prevent leaks.
On any failure during socket binding or event registration, both `udp_fd` and `server_addr` should be released to avoid leaking system resources.
Previously, if `addr_bind()`, `event_new()`, or `event_add()` failed, the function would return early without closing the socket or freeing memory, causing file descriptor and heap memory leaks.
This patch addresses overlooked memory and resource cleanup on failure paths, improving server stability …
> Fix memory and resource leaks in udp_create_server_socket( )
