coturn/coturn

src/apps/relay/ns_ioalib_engine_impl.c
If you configure coturn without openssl, there is a single usage of check_tentative_tls here https://github.com/coturn/coturn/blob/master/src/apps/relay/ns_ioalib_engine_impl.c on line 3316 which is not covered by a `#if TLS_SUPPORTED` macro, causing a check_tentative_tls undefined error.
=> case call to check_tentative_tls with TLS_SUPPORTED

src/apps/relay/mainrelay.c
Fix an issue with parameter initialization in the previous pull requests.
Previously it was working fine as long as the parameter was passed on the command line, but would fallback on 0 instead of the default value when the parameter was absent.
=> fix #63 issue

src/client/ns_turn_msg.c
The initialization was on the memory we received in parameter, but this memory will get copied later in map_addr_from_public_to_private.
However the source of the copy, public_addr is never initialized.
=> fix memory initialization in src/client/ns_turn_msg.c in function stun_attr_get_addr_str

src/apps/relay/mainrelay.c, src/apps/relay/mainrelay.h, src/apps/relay/netengine.c, src/apps/relay/turn_admin_server.c, src/server/ns_turn_server.c, src/server/ns_turn_server.h
It will hide turnserver version (like apache does).
This is a common corporate security requirement.
=> Add "--prod" to turnserver command-line options.

make-man.sh
Changes from cd's to pushd/popd
Switches from hardcoding to script looping
Changed the rm call to act on manpages (.1) files only which adds a bit of safety while still doing the job
*Note
Removing the file redirection from the last `popd >/dev/null 2>&1` echoes the current working directory so if needed for compatibility with the env, a little comment and extra line would then properly define the var.
```shell
#popd >/dev/null 2>&1
CPWD=$(popd)
```
=> Updates make-man.sh

src/apps/relay/mainrelay.c
Fixes #113.
Credit for the fix goes to @davidben.
=> Typo in the ALPN callback: ta_len should be ha_len

src/apps/relay/ns_ioalib_engine_impl.c, turndb/schema.stats.redis
Publish total traffic information when an allocation is deleted. This
makes it easier for applications to monitor total usage per session.
=> Report total traffic used per allocation via Redis

examples/etc/turnserver.conf
Must be used with long-term credentials mechanism or with TURN REST API.
=> Add the realm parameter in the example config file

src/apps/relay/mainrelay.c
I found that if I use `lt-cred-mech` and `use-auth-secret` option both, only `use-auth-secret`'s behavior is appeared and credentials in `turnusers_lt` table are disabled.
I think this should be alarmed with warning.
Thanks.
=> config warning about both using use-auth-secret and lt-cred-mech

src/apps/relay/ns_ioalib_engine_impl.c, src/server/ns_turn_ioalib.h, src/server/ns_turn_server.c
Call turn_report_session_usage() from shutdown_client_connection(), so
that any accumulated packets and data sent/received gets added to the
totals before passing it to report_turn_session_info(). This also
ensures that the total_traffic message sent to redis contains correct
values.
Add a force_invalid argument to turn_report_session_usage() to ensure
that report_turn_session_info() is still called when the former is
called from shutdown_client_connection(). This should avoid any
unexpected change in behavior.
=> Update total usage on client shutdown

src/apps/relay/mainrelay.c, src/apps/relay/mainrelay.h, src/apps/relay/netengine.c, src/apps/relay/ns_ioalib_engine_impl.c, src/apps/relay/ns_ioalib_impl.h
This commit does the following:
* Factor out loading of TLS keys and certificates into turn_params SSL
context so that it can be repeated. (Contexts are not overwritten
when loading encounters errors, but initial contexts will be set
regardless of errors. This keeps existing semantics.)
* Isolate copying of turn_params SSL context to ioa_engine structs
into callback functions appropriate for libevent invocation.
* Chain both of the above to a signal event handler responding to
SIGUSR2.
This allows replacement of keys and certificates during run-time
without interrupting relaying operations.
=> Make SIGUSR2 reload TLS certificates

src/apps/relay/mainrelay.c
find_config_file() now uses the "pass" variable to avoid printing "log file opened" to the log file during first pass of read_config_file() before logging is actually configured.
Moved print_features() behind both read_config_file() calls, so that the output goes to the configured log file.
=> Do not write to log before logging configuration is read from a config file

examples/etc/turnserver.conf
The comment before the TURN REST API flag was confusing: it seemed to imply that `use-auth-secret` _required_ the use of `lt-cred-mech`, but I've since learnt from PR #160 that in fact you're not supposed to use both of them together.
(I suspect that this was why lots of sample coturn config files you can find on the internet have both of those flags set.)
=> Update the example config file: use-auth-secret overrides lt-cred-mech.

src/apps/relay/mainrelay.c
There is a small memory leak in the read_config_file (mainrelay.c:1603) function.
The function find_config_file() returns a malloc'ed string which is not freed.
https://github.com/coturn/coturn/blob/5d88f8275df4fa27236cc219d526c9e09d89815c/src/apps/relay/mainrelay.c#L1603
Valgrind result:
> ==36711== 31 bytes in 1 blocks are definitely lost in loss record 603 of 885
==36711==    at 0x4C2BBAF: malloc (vg_replace_malloc.c:299)
==36711==    by 0x14C560: find_config_file (apputils.c:827)
==36711==    by 0x11E944: read_config_file (mainrelay.c:1603)
==36711==    by 0x11FCE2: main (mainrelay.c:2128)
==36711== 
==36711== 31 bytes in 1 blocks are definitely lost in loss record 604 of 885
==36711==    at 0x4C2BBAF: malloc (vg_replace_malloc.c:299)
==36711==    by 0x14C560: find_config_file …
=> Fix memory leak in read_config_file

src/apps/relay/turn_admin_server.c
Fixed missed \r\n symbols in HTTP headers from HTTPS management interface when no admin users defined
=> Fixed missed \r\n symbols in HTTP headers from HTTPS management UI

src/apps/relay/mainrelay.c, src/apps/relay/turn_admin_server.c, src/apps/relay/turn_admin_server.h, src/server/ns_turn_server.c
Hello,
I've moved the https web-admin interface to a dedicated ip:port, rather than the standard STUN ports. I added 3 new options to configure this:
`--no-web-admin (default: web-admin is enabled)`
`--web-admin-ip=<IP> (default: 127.0.0.1)`
`--web-admin-port=<port> (default: 8080)`
Thanks for reviewing & hope it will help.
Thibaut.
=> Move web-admin interface to dedicated (and configurable) ip:port

src/apps/relay/mainrelay.c
Configfile lines with filenames for example could have a trailing white space,
which most editors don't show. The user gets "file not found" which is not 
trivial to debug, because this white space is almost invisible in the logfile also.
I suggest to strip white spaces at config file line ends for convenience of the sysadmins.
If you really need a white space in an config file value you might use the arg="value " syntax.
=> strip white-spaces from config file lines end

src/apps/relay/turn_admin_server.c
Hello,
The web-admin handler "/update", used to add/delete ip permissions per realm, contains a sql-injection.
The URL parameters "dipk" and "aipk" (ip permission kind to delete/add) are taken from the URL and directly passed to the DB drivers (which most of them use this value as a table/collection prefix directly)
For example I was able to delete any of my sqlite tables with a simple forged GET request.
Of course, you need to be logged first, so the criticity is very limited, but if I send the forged link to an admin connected to the web-admin interface, if the admin open the link, he will delete the entries for me (because this request is a simple GET and not a POST).
To prevent this, I added simple checks because this "ip kind" value MUST be either "allowed" or "denied". Anything else …
=> fix the webadmin ip permission add/delete sql injection

src/apps/relay/dbdrivers/dbd_mongo.c
Hello, 
When configuring the --mongo-userdb (or -J) parameter to something invalid, like `127.0.0.1/coturn` instead of `mongodb://127.0.0.1/coturn` for example,
both the turnserver and the turnadmin command crash (see trace below).
Inside the mongo driver, the struct MONGO is allocated but not zero-ed so when trying to free some of its fields in MongoFree() method (in case of failure for example), it result in freeing undefined data. The fix is to zeromem the newly allocated structure.
> 0: ERROR: Cannot open parse MongoDB URI <127.0.0.1/coturn>, connection string format error
> *** Error in `./bin/turnserver': free(): invalid pointer: 0x00007fbb900001d8 ***
> ======= Backtrace: =========
> /lib/x86_64-linux-gnu/libc.so.6(+0x70bfb)[0x7fbbaf1c5bfb]
> …
=> fix mongo driver crash when invalid connection string is used

src/apps/relay/mainrelay.c
Hi,
Return value of fread function is not zero on success therefore I modified these sections.
Check:
The paragraph shown below quoted from: http://man7.org/linux/man-pages/man3/fwrite.3.html
RETURN VALUE 
On success, fread() and fwrite() return the number of items read or
written.  This number equals the number of bytes transferred only
when size is 1.  If an error occurs, or the end of the file is
reached, the return value is a short item count (or zero).
Thanks for review
Selahaddin
=> Wrong fread usage

src/apps/relay/dbdrivers/dbd_mongo.c, src/apps/relay/dbdrivers/dbd_mysql.c, src/apps/relay/dbdrivers/dbd_pgsql.c, src/apps/relay/dbdrivers/dbd_redis.c, src/apps/relay/dbdrivers/dbd_sqlite.c, src/apps/relay/dbdrivers/dbdriver.h, src/apps/relay/mainrelay.c
Coturn does not disconnect database properly when shutdown.
This behavior causes accumulation of sockets for database with TIME_WAIT.
Especially, `turnadmin` is recommended to manage userdb,
but use of `turnadmin` from other application or scripts
can run out of socket resource due to above problem.
This patch adds database disconnection when shutdown
for both of `turnserver` and `turnadmin`.
Fixes #366
=> Disconnect database gracefully

src/apps/common/apputils.c
Hi,
I need to compile Turn Server with BoringSSL.
BoringSSL does not have "SSL_get_ssl_method" function. But both OpenSSL and BoringSSL has a function named as "SSL_get_version" which is returns a string describing the TLS version used by |ssl|.
We can use this function for getting tls version for BoringSSL compatibility
Thanks for reviewing.
Selahaddin.
=> Using SSL_get_version method for BoringSSL compatibility

src/apps/relay/ns_ioalib_engine_impl.c, src/server/ns_turn_server.c, src/server/ns_turn_session.h, turndb/schema.stats.redis
I needed to track all outgoing bandwidth so I expanded the bandwidth reporting to also report bandwidth used by peers. The traffic is reported separately from the client traffic so no existing functionality is changed. 
The redis keys for the peer data are: 
/turn/realm/[realm]/user/[user]/allocation/[allocation]/traffic/peer
/turn/realm/[realm]/user/[user]/allocation/[allocation]/total_traffic/peer
/turn/user/[user]/allocation/[allocation]/traffic/peer
/turn/user/[user]/allocation/[allocation]/total_traffic/peer
I tested with the turnutils_uclient and turnutils_peer for both tcp and udp connections and everything seems correct. I was not able to test passive tcp because I don't really know what it is and when I try and start the turnutils_uclient with -P I get errors.
=> added bandwidth usage reporting for bandwidth used by peers

src/apps/common/ns_turn_utils.c
ssh length should be 3, but checking for 4. So updated memcmp method to 3 instead of 4.
=> Updated incorrect string length check for 'ssh'

src/client/ns_turn_msg.c
Deallocating `str` happens at the end of the function, so don't skip it when encountering an unsupported `SHATYPE`.
=> Fix a memory leak when an SHATYPE isn't supported

src/client/ns_turn_msg.c, src/client/ns_turn_msg.h
These fix a few issues when compiling coturn with high level warnings enabled as well as allowing users to pass constant data as parameters to (some) functions that do not mutate them.
=> Compiler warning fixes

src/apps/common/apputils.c
There is a null check for the first char fn[0], but missing for second char fn[1], so added null check for the second character before access.
=> added null check for second char

examples/etc/turnserver.conf
Edited turnserver.conf to fix typos and grammar and clarify explanations of various options for documentation.
=> Updated turnserver.conf to fix typos and grammar to clarify documentation. 

docker/coturn/turnserver.conf, examples/etc/turnserver.conf
As reported by [RFC:](https://tools.ietf.org/html/rfc5389#section-16.1.2)
```
Revealing the specific software version of the agent through the
SOFTWARE attribute might allow them to become more vulnerable to
attacks against software that is known to contain security holes.
Implementers SHOULD make usage of the SOFTWARE attribute a
configurable option.
```
Just add `prod` to the configuration file to hide software version in Binding Success Response
=> turnserver.conf: add --prod section to enhance security

src/client/ns_turn_msg.c
The STUN attribute API wasn't checking that the size the buffer reported itself to be was not greater than the size of the buffer available, and `stun_attr_ref`s were not size-checked before being returned to the caller.
=> Add additional input validation for STUN messages

src/client/ns_turn_msg.c
This is one of those special cases where a non approved cryptographic
algorithm is allowed when operating in FIPS mode. Inform OpenSSL that
this is the case.
In the STUN RFC the long-term credential mechanism requires that the key
used in the HMAC-SHA1 generation be the MD5 of specific values:
https://tools.ietf.org/html/rfc5389#section-15.4
Since this is obfuscating parameters to be used in an approved
cryptographic algorithm, this is allowed usage per the [FIPS 140-2 Implementation Guidance](https://csrc.nist.gov/csrc/media/projects/cryptographic-module-validation-program/documents/fips140-2/fips1402ig.pdf).
See page 81.
Without this change, coturn crashes when trying to set up any long-term
credential mechanism.
=> Allow MD5 in FIPS mode

src/apps/relay/mainrelay.c
Fix related to POS36-C and rpmlint error "missing-call-to-setgroups-before-setuid".
=> Drop of supplementary group IDs

README.turnserver, docker/coturn/turnserver.conf, examples/etc/turnserver.conf, man/man1/turnserver.1, src/apps/relay/mainrelay.c, src/apps/relay/mainrelay.h, src/apps/relay/netengine.c, src/apps/relay/turn_admin_server.c, src/server/ns_turn_server.c, src/server/ns_turn_server.h
As discussed in #478, if the parameter only controls whether or not to send the software attribute and not other production-relevant configurations, it should be named accordingly.
The old --prod configuration option still works, but is now deprecated and undocumented.
=> Rename "prod" config option to "no-software-attribute"

examples/scripts/pack.sh
Hello! 
The latest release [https://coturn.net/turnserver/v4.5.1.2/turnserver-4.5.1.2.tar.gz] has a lot of Mac metadata files (._*).
This fix tells tar to not include the metadata into the release archive.
=> tell tar to not include the metadata into release

examples/etc/turnserver.conf
Judging from the information provided here https://github.com/coturn/coturn/issues/220#issuecomment-371916988,
SSL isn't supported anymore so the reference should be removed from the config file.
=> Remove reference to SSLv3

src/client/ns_turn_msg.c
Hi,
These lines added to allow MD5 for OpenSSL in FIPS mode previously but BoringSSL does not allow MD5 in FIPS mode. So, I added definition check to chek MD5 support of SSL library for BoringSSL compatibility.
Thanks for reviewing.
Selahaddin.
=> Ignore MD5 for BoringSSL

rpm/build.settings.sh, rpm/build.sh
Hello! 
RPM package build script always uses the master git repo, so it makes it hard to add local patches.
I had faced up with issue #556 and was surprised that my attempts to fix it ignored. So, I had to make this patch to have an ability to resolve the RPM-issue.
=> build RPM from local folder instead of git repo

docker/coturn/turnserver.conf, examples/etc/turnserver.conf
FYI, this patch was created by doing `M-x delete-trailing-whitespace` in GNU Emacs.
=> Delete trailing whitespace in example configuration files

README.turnserver
While that prometheus exporter was initially enabled by default, it looks like there's been a change of plan, resulting in some inconsistencies in the doc.
The `--no-prometheus` option was replaced by a `--prometheus` one -- according to https://github.com/wolmi/coturn/blob/master/src/apps/relay/mainrelay.c#L540
=> Fix misleading option in doc

src/apps/relay/ns_ioalib_engine_impl.c
This point in the code was making a best-effort attempt to reject TLS connections on non-TLS listeners.
After this is merged, it will skip this check when the socket is being used for RFC6062 TCP relay data.  That data should be opaque for the TURN server and it is fine if it happens to be (or look like) TLS.
Fixes #605 .
=> Allow RFC6062 TCP relay data to look like TLS; fixes #605

src/apps/relay/ns_ioalib_engine_impl.c
I recently found that Nginx only supports Proxy Protocol V1 when initiating connections and Coturn only supports Proxy Protocol V2.
This patch adds support for Proxy Protocol V1. The code looks for Proxy Protocol V2 first, if that fails, then looks for V1 before aborting the connection.
=> Add support for proxy protocol V1

src/apps/common/ns_turn_utils.c, src/apps/common/ns_turn_utils.h, src/apps/relay/mainrelay.c
The 'number of seconds since the daemon was started' is amusing and compact, but it hinders debugging and correlation with other events.  This implements logs that use a complete `YYYY-MM-DDTHH:MM:SS` output which is easy to read and correlate.
Signed-off-by: Paul Wayper <paulway@mabula.net>
=> Print full date and time in logs

src/apps/common/ns_turn_openssl.h, src/apps/relay/ns_ioalib_engine_impl.c, src/client/ns_turn_msg.c
=> Do not use FIPS and remove hardcode OPENSSL_VERSION_NUMBER with LibreSSL

src/ns_turn_defs.h
You must define `__APPLE_USE_RFC_3542` in order to use the `IPV6_DONTFRAG` sockopt: https://opensource.apple.com/source/xnu/xnu-6153.141.1/bsd/netinet6/in6.h.auto.html
```
* To use the new IPv6 Sockets options introduced by RFC 3542
* the constant __APPLE_USE_RFC_3542 must be defined before
* including <netinet/in.h>
```
=> fix compilation on macOS Big Sur

configure, src/apps/relay/acme.c, src/apps/relay/acme.h
The #551 PR rewrite/current implementation has several issues:
- unsafe copy of req:
- the src pointer for the `req_url` copy may point to anything else, but not the intended location
- the length of `req` is not checked and thus may overflow the `req_url` buffer
- too much redundant work
- there is no need to search for space[s] or tab[s] to extract the URL path: `is_acme_req()` already takes care of it. It returns the position of the 2nd space of the request-line (see `plen`, RFC 2616, 5.1. The first space gets covered by the `GET_ACME_PREFIX`). If the request is not RFC conform, we do not care - ignore it.
- since we already know the url (req + 4, plen), there is no need to copy those bytes around and no need for all the related helper vars
- inconsistency:
- …
=> fix acme wrt. security, redundancy, consistency

configure
I've changed the configure script to use pkg-config.
I've tested building on:
- Fedora 29 using various shells (bash/dash/busybox), with everything/everything disabled/mixed used/disabled/unavailable
- CentOS 6.10 with SQLite
-  NetBSD 7.2 with SQLite and MongoDB
Fixes #152.
=> configure: pkg-config, various cleanups

turndb/schema.userdb.redis
Hi.
A couple of days ago I asked what's the hash algorithm for the value stored in Redis for long-term credentials (#681). Thanks to @misi for the answer, it helped me a lot! but I think that's something that can be added to the docs in the schema.userdb.redis file. So that's pretty much what this PR does.
=> Add hash algorithm for key value to redis userdb schema docs

debian/coturn.postrm
This fixes a regression introduced in commit b9a4a8.
When trying to remove a dpkg-statoverride, we need to check,
whether it exists. Otherwise it's failing, as can be observed
via piuparts runs:
| dpkg: unrecoverable fatal error, aborting:
|  unknown system group 'turnserver' in statoverride file; the system group got removed
| before the override, which is most probably a packaging bug, to recover you
| can remove the override manually with dpkg-statoverride
| E: Sub-process /usr/bin/dpkg returned an error code (2)
Closes: #981330
=> debian/coturn.postrm: fix check for dpkg-statoverride on package removal

src/apps/common/ns_turn_utils.c
In commit 599a61ee this was removed, by accident it could seem.
=> Restore no_stdout_log behaviour

configure
Hi,
on a system with an older version of mysql and mysql-libs (RHEL6 / mysql version 5.1.x) there is no pkg-config file available for mysql.
This patch fallback on using mysql_config if it is found in PATH.
=> Support older mysql client version in configure

configure
This script looks like it's designed to use a portable subset of
sh; I'm not aware of any portability problems of this patch.
=> Packaging scripts can miss out on these errors

docker/coturn/Dockerfile
**The current version of mongoc is old, many options of the connection string are not available.**
This pr change the way the image is built:
- use debian slim (this and other optimizations reduce the production image size, 750Mo =>  130Mo)
- add a stage production (I don't see the point of installing mongodb inside the image, maybe something I didn't get)
- build mongoc to get a 1.17.4 version
- remove the exposed ports on the production image, if you use a network host you don't need them and this makes the start of the image really slow even if the user doesn't need all those ports exposed.
=> mongoc version 1.17.4

configure, docker/coturn/CHANGELOG.md, docker/coturn/Makefile, docker/coturn/alpine/Dockerfile, docker/coturn/debian/Dockerfile, docker/coturn/tests/main.bats
Fixes instrumentisto/coturn-docker-image#37
Superseeds instrumentisto/coturn-docker-image#39
This PR is based on @SammyEnigma's work, with a few improvements:
- use upstream original repo instead of a fork
- test prometheus support
=> Support Prometheus in Docker image

src/apps/relay/dtls_listener.c, src/apps/relay/dtls_listener.h, src/apps/relay/mainrelay.c, src/apps/relay/netengine.c
The process  would run for a while, but eventually crash. valgrind shows a bug immediately, but memory (re-)use means that actual effect can be mostly invisible (tested on musl libc).
Each patch explains. We've been running these patches for a while now, but I just rebased them to the most recent coturn.
=> SSL reload has hidden bugs which cause crashes

.github/workflows/docker.yml, docker/coturn/Makefile, docker/coturn/alpine/Dockerfile, docker/coturn/debian/Dockerfile
I have added labels to the image so that it is explicit which revision was used to build a container.
I have also tweaked the Dockerfile to work better when you have forked the repository.
=> Store git version information in Docker image metadata

docker/coturn/README.md
The default Docker coturn config enables usage of port 5349. I'd say the readme needs to reflect that.
=> Add port 5349 to Docker readme

debian/control, debian/copyright, debian/upstream/metadata
Fix some issues reported by lintian
* debian/copyright: use spaces rather than tabs to start continuation lines. ([tab-in-license-text](https://lintian.debian.org/tags/tab-in-license-text))
* Remove obsolete field Name from debian/upstream/metadata (already present in machine-readable debian/copyright).
* Update standards version to 4.6.0, no changes needed. ([out-of-date-standards-version](https://lintian.debian.org/tags/out-of-date-standards-version))
This merge proposal was created automatically by the [Janitor bot](https://janitor.debian.net/lintian-fixes).
For more information, including instructions on how to disable
these merge proposals, see https://janitor.debian.net/lintian-fixes.
You can follow up to this merge proposal as you normally would.
The bot will automatically update …
=> Fix some issues reported by lintian

README.turnserver, man/man1/turnserver.1, src/apps/relay/mainrelay.c, src/apps/relay/mainrelay.h, src/apps/relay/prom_server.c
This introduces a new `--prometheus-port` parameter. Default values is still `9641`.
=> Add ability to configure prometheus listener port

README.turnserver, man/man1/turnserver.1, src/apps/relay/mainrelay.c, src/apps/relay/mainrelay.h, src/apps/relay/prom_server.c
When Prometheus metrics are enabled, traffic metrics are labelled with client username, which permits tracking traffic usage on a per-client basis. However, the TURN REST API authentication scheme uses ephemeral usernames, and so authenticating with a new username will cause a new label value to be generated. As prometheus-client-c doesn't garbage collect old metrics labels, this means that memory usage will grow over time, corresponding to clients authenticating with new usernames.
This change adds a new option `--prometheus-no-username-labels`, which will disable the use of username labels when traffic metrics are record, which should eliminate the memory leak issue. This should address issue #666.
=> Configurable username labelling in Prometheus metrics

src/apps/relay/ns_ioalib_engine_impl.c
After testing the latest docker image I noticed segfaults appearing at random moments. The segfault is reproducible under this conditions:
- one client with an allocation redirecting the requests to a local webservice
- 150 concurrent peer requests executed with siege (a cli http benchmark tool)
Under normal conditions the segfault appears only under concurrent use (~150 users), but running coturn with valgrind leads to a deterministic memory access error with just one peer request.
The cause lies in `ns_turn_server.c` in `tcp_peer_accept_connection() `
```
tc->peer_s = s;
...
set_ioa_socket_sub_session(s,tc);
```
After this there is a cycle between the `ioa_socket_handle s` and the `tcp_connection tc`. `tc->peer_s->sub_session == tc`
Now the actual erroneous assignment happens in the …
=> Fixed assignment to freed memory leading to a segfault

configure
libintl isn't used, so there is no need to link coturn to it.
Signed-off-by: Sebastian Kemper <sebastian_ml@gmx.net>
Hi all,
We realized in [OpenWrt telephony repo](https://github.com/openwrt/telephony/pull/725) that coturn links to libintl even though it's not actually using it. In favor of a small footprint I'd suggest to drop the intl test from configure.
Kind regards,
Seb
=> configure: don't link in libintl

src/apps/relay/ns_ioalib_engine_impl.c, src/apps/relay/prom_server.c, src/apps/relay/prom_server.h
Hello, I would like to propose new metric to prometheus: it is the gauge metric of total current allocations number. It doesn't create any detailed lables in order not to increase memory consumption and only keeps one counter. I believe it may be useful e.g. for draining coturn instance before termination by auto-scaling group or simply as one of the current load metrics.
Thank you for your attention!
=> Add current allocations number gauge metric

src/apps/uclient/mainuclient.c
If none of -e and -y options are specified, currently client sends peer address 0.0.0.0:some_port to turn server, which results in Forbidden IP error in 4.5.2.
Since the turn server didn't return any errors until 4.5.1.x, there are some misunderstanding examples lacking these options (and misleading Q&As around Issues and stackoverflow etc.: `use 4.5.1.3` ).
This adds an error message to guide users to specify either -e or -y option.
=> uclient: Show error on invalid peer options specification

src/apps/relay/ns_ioalib_engine_impl.c
SSL will become opaque in LibreSSL 3.4.x, hence the code reaching inside
it will result in build breakage.
SSL_set0_rbio() now available in libressl.
=> Fix build with libressl 3.4.0+

src/apps/relay/ns_ioalib_engine_impl.c, src/client/ns_turn_msg.c
Overall flamegraph:![image](https://user-images.githubusercontent.com/180439/119133333-c48d5200-ba09-11eb-81ec-4c8f5ae4a605.png)
Zoom in on udp_server_input_handler:
Zoom in on socket_input_handler:
In the above flamegraphs you can see that the majority of time in **udp_server_input_handler** and **socket_input_handler** is being spent in memset. This is because both eventually call **new_blist_elem()** which ends up zeroing the entire stun_buffer_list_elem struct before returning. The stun_buffer_list_elem is almost 64kb in size and this causes performance issues on high traffic servers.
With this change, we zero out any padding bytes explicitly in stun_attr_add_str() and avoid zeroing out the entire stun buffer.
=> Fix for performance regression caused by CVE-2020-4067 fix

docker/coturn/turnserver.conf, examples/etc/turnserver.conf
Sample configuration file mentions --dh2066 which does not exist in code (assumed by default when --dh1066 and --dh566 are omitted and no --dh-file is provided)
Fixes #550 
Test Plan:
N/A
=> Update example turnserver.conf file to reflect that dh2066 is default

src/apps/relay/dtls_listener.c, src/apps/relay/ns_ioalib_engine_impl.c
Disable SSL renegotiation by setting `SSL_OP_NO_RENEGOTIATION` on SSL connection (both TLS and DTLS)
Fixes #892
Tested by connecting to running server and asking for renegotiation:
```
#openssl s_client -connect localhost:443
...
---
RENEGOTIATING
4398376448:error:14094153:SSL routines:ssl3_read_bytes:no renegotiation:ssl/record/rec_layer_s3.c:1561:
```
and DTLS
```
#openssl s_client -connect localhost:443 -dtls1
...
---
RENEGOTIATING
4572587520:error:14102199:SSL routines:dtls1_read_bytes:too many warn alerts:ssl/record/rec_layer_d1.c:586:
```
=> Disable SSL renegotiation

src/apps/common/CMakeLists.txt
Maybe only one is strictly required, but the list of headers used in `ns_turn_openssl.h` includes things from both targets.
I think this correctly resolves #242. I can now compile coturn on MacOS without having to manually specify any `-I` include directory for OpenSSL. (I do specify `OPENSSL_ROOT_DIR`, of course.)
How come this works on Linux? Is the `Libevent::openssl` target forwarding the OpenSSL include directories?
That's another line of investigation if you don't like this solution.
=> [turncommon] depend on OpenSSL

CMakeLists.txt
macOS does not have `pthread_barrier_*` so need to define `TURN_NO_THREAD_BARRIERS` as a workaround
Fixes #946 
Tests plan: 
- run cmake to generate make files
- run make to build turnserver
- run `examples/run_tests.sh` and pass successfully
=> Fix cmake build on macOS

src/server/ns_turn_server.c
Actually, as below, before fixing, the sessions_map may be larger and larger when register_callback_on_ioa_socket inside open_client_connection_session retrun -1. The reason is that, if register_callback_on_ioa_socket return -1, no read/write/ event will be registered and no timeout event will be registered, in this case, the session will never be deleted from sessions_map.
After fixing, when register_callback_on_ioa_socket fail，it doesn't return immediately, instead, we still register client_to_be_allocated_timeout_handler in the next step of open_client_connection_session. In this case, the unuseful session will be deleted and freed after timeout. 
@eakraly @ggarber
=> fix turn session leak

examples/run_tests.sh
Typo that caused UDP test to actually run TCP
=> Fix duplicate TCP flag in run_tests.sh script

src/apps/relay/turn_admin_server.c
Writing outside of a buffer can only happen if incoming HTTP request is longer than UDP_STUN_BUFFER_SIZE (16KB).
This change validates that the request is no longer than the buffer size and drops it if it is the case
Fixes #342
Test plan:
- Run in debugger and send a 16KB request using curl - response returns, logs correct
- Send 16KB + 1b request - warning logged and request dropped
=> Do not write outside of a buffer in admin interface

src/apps/relay/mainrelay.c
Print number version of the build
```
$ turnserver --version
4.5.2
```
Closes #843
=> Print turnserver version with `--version`

src/apps/common/ns_turn_utils.c
`vsnprintf` will stop at the max buffer size as provided in its 2nd argument
But the return value is `The number of characters that would have been written if n had been sufficiently large` meaning it can be larger than actual buffer size
`fwrite` will actually use the larger, incorrect number and dump unrelated memory to log (and crash with high confidence)
Test:
- Query admin interface with super long path (>16KB) - crash
- With the fix - no crash with the same input, log line cut off
=> Fix long log line printing

src/apps/common/hiredis_libevent2.c, src/apps/relay/mainrelay.c, src/apps/relay/tls_listener.c, src/client/ns_turn_msg.c
- Redundant checks for variable values
- Potential nullptr dereference
- Double check for the same variable
Run with:
```
cppcheck --inline-suppr --language=c --enable=warning,performance --force .
```
=> Fix small issues reported by cppcheck

src/ns_turn_defs.h
Increase the version number for the 4.6.0 release.
It uses the codename Gorst.
=> Increase version to 4.6.0

configure
- Preserve file timestamps when using `install`
- Use permissions `0644` rather than default `0755` for installing man pages
The alternative calls of `cp` are using `cp -p` as well (if `install` is unavailable).
=> Preserve file timestamps when using install(1)

src/apps/relay/ns_ioalib_engine_impl.c, src/apps/uclient/startuclient.c, src/client/ns_turn_msg.c
openssl-3.0 deprecated some APIs and introduced new APIs instead:
`SSL_get_peer_certificate ` -> `SSL_get1_peer_certificate `
`FIPS_mode()`->`EVP_default_properties_is_fips_enabled()`
`EVP_MD_CTX_set_flags()`->`EVP_default_properties_enable_fips()` specifically for enabling FIPS mode
This change should workaround that by ifdef-ing old/new versions of openssl and APIs - so pre-3.0 use existing APIs (so not change there) and >=3.0 will use new APIs (whether it actually works or not is still TBD as this is just a first step in openssl-3.0 support)
Should fix #886
Test Plan:
Run CI build that supports ubuntu-20.04 (openssl-1.1.1) and ubuntu-22.04 (openssl-3.0.2)
Both builds pass
None of them have FIPS support (which for 1.1.x stays the same as before)
=> Improve openssl3 and FIPS support

src/apps/relay/netengine.c
There are too many defines that are, eventually, used in one place so just inlining.
Current code generates following warning:
```
warning: macro expansion producing 'defined' has undefined behavior [-Wexpansion-to-defined]
```
With the fix there is no warning
=> Fix a warning

src/apps/common/apputils.c, src/apps/common/hiredis_libevent2.c, src/apps/common/stun_buffer.c, src/apps/natdiscovery/natdiscovery.c, src/apps/oauth/oauth.c, src/apps/peer/udpserver.c, src/apps/relay/dbdrivers/dbd_mongo.c, src/apps/relay/dbdrivers/dbd_mysql.c, src/apps/relay/dbdrivers/dbd_redis.c, src/apps/relay/dtls_listener.c, src/apps/relay/http_server.c, src/apps/relay/mainrelay.c, src/apps/relay/netengine.c, src/apps/relay/ns_ioalib_engine_impl.c, src/apps/relay/turn_admin_server.c, src/apps/relay/userdb.c, src/apps/rfc5769/rfc5769check.c, src/apps/stunclient/stunclient.c, src/apps/uclient/mainuclient.c, src/apps/uclient/startuclient.c, src/apps/uclient/uclient.c, src/client/ns_turn_ioaddr.c, src/client/ns_turn_msg.c, src/server/ns_turn_allocation.c, src/server/ns_turn_maps.c, src/server/ns_turn_maps_rtcp.c, src/server/ns_turn_server.c
Replace all instances of `bzero` with memset by find-replace-edit.
This is straightforward replacement which is suboptimal in a few cases (for example we could use calloc instead of malloc+memset(0))
Inspired by #855
=> Replace bzero with memset

.github/workflows/tests.yml
This should help catching issues like the one in #978 with older versions of openssl or other libraries used
=> Add CI tests in older ubuntu version

src/apps/common/apputils.c, src/apps/common/ns_turn_utils.c, src/apps/relay/acme.c, src/apps/relay/dbdrivers/dbd_mongo.c, src/apps/relay/dbdrivers/dbd_mysql.c, src/apps/relay/http_server.c, src/apps/relay/netengine.c, src/apps/relay/ns_ioalib_engine_impl.c, src/apps/relay/tls_listener.c, src/apps/relay/turn_admin_server.c, src/apps/relay/userdb.c, src/apps/uclient/mainuclient.c, src/apps/uclient/startuclient.c, src/apps/uclient/uclient.c, src/client++/TurnMsgLib.h, src/client/ns_turn_ioaddr.c, src/client/ns_turn_msg.c, src/client/ns_turn_msg_addr.c, src/server/ns_turn_allocation.c, src/server/ns_turn_maps.c, src/server/ns_turn_server.c
Replace all instances of `bcopy` with memcpy.
Inspired by https://github.com/coturn/coturn/pull/855
=> Replace bcopy with memcpy

src/apps/relay/prom_server.c
Before:
```
./bin/turnserver --prometheus -m 32
...
Socket descriptor larger than FD_SETSIZE: 2660 > 1024
0: : ERROR: Could not start Prometheus collector!
```
After:
```
./bin/turnserver --prometheus -m 32
...
0: : Prometheus collector started successfully.
```
Also added `MHD_USE_ERROR_LOG` so the actual problems during startup of promhttp are printed. Without it the `Socket descriptor larger than FD_SETSIZE: 2660 > 1024` error was not visible and finding the cause of the startup problems of promhttp was not obvious at first.
=> Use epoll for promhttp server if supported. 

.github/workflows/cmake.yaml, .github/workflows/tests.yml, src/apps/relay/prom_server.c
Install dependencies and build with prometheus support during CI builds
Ubuntu 16.04 has issues supporting `MHD_USE_EPOLL_INTERNAL_THREAD` so disabling it (using SELECT)
Should not impact anything as the only reason we use Ubuntu 16.04 is to validate build against openssl-1.0.2
Fixes  #998
=> Build CI with prometheus support

src/server/ns_turn_server.c
Hello, and thank you for this great project!
When sending a mobility refresh request, the server is responding with an invalid stun packet. Specifically, only the last 24 bytes generated for message integrity are sent.
Request:
Response:
This appears to be caused by the buffer length not being updated when `STUN_ATTRIBUTE_SOFTWARE` is added to the response, as it's being assigned to a `len` variable scoped to that conditional. 
As a result, the next call to `stun_get_command_message_len_str` when handling message integrity returns `-1` and resizes the buffer, etc.
Passing in the original `len` to `stun_attr_add_str` for attribute software fixes the issue, but apologies if this is not the right way to fix this!
=> Malformed response to mobility refresh request

examples/run_tests.sh, src/apps/relay/dtls_listener.c, src/apps/relay/mainrelay.c, src/apps/relay/mainrelay.h, src/apps/relay/netengine.c, src/apps/relay/ns_ioalib_impl.h
Similar to #989, use a single SSL context for all versions of DTLS protocol
- Add support for modern API (protocol version independent APIs)
- Add DTLS test to the CI test
- Removing calls to `SSL_CTX_set_read_ahead` in DTLS context (does nothing as DTLS is datagram protocol - we always get the whole datagram so this call has no impact)
Fixes #924
=> Use single SSL_CTX for DTLS support

src/apps/common/apputils.c, src/apps/common/hiredis_libevent2.c, src/apps/oauth/oauth.c, src/apps/relay/dbdrivers/dbd_sqlite.c, src/apps/relay/libtelnet.c, src/apps/relay/turn_admin_server.c, src/apps/relay/userdb.c, src/apps/uclient/mainuclient.c, src/server/ns_turn_maps_rtcp.c, src/server/ns_turn_server.c
Using clang-tidy to detect unused header files
Inspired by #855
Test Plan:
- Rebuild all on mac, review no warnings/errors
- Pass builds/docker build - review for no issues
=> Cleanup unused include of header files

src/apps/relay/dbdrivers/dbd_redis.c, src/apps/relay/netengine.c
This code is in as back as git can see. Removed for now as it has no use at all.
Also reduces traffic to redis (though will not reduce any load on redis)
Refs #150
=> Remove debug publish to redis

src/apps/relay/libtelnet.c
Run build - bunch of warnings gone (signed/unsigned type mismatch)
=> Fix multiple warnings in libtelnet.c file

src/client/ns_turn_msg.c
```
==6418==WARNING: MemorySanitizer: use-of-uninitialized-value
#0 0x4e7530 in bcmp /src/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_common_interceptors.inc:906:10
#1 0x55463d in stun_check_message_integrity_by_key_str coturn/src/client/ns_turn_msg.c:1989:5
#2 0x554acc in stun_check_message_integrity_str coturn/src/client/ns_turn_msg.c:2008:9
#3 0x5358c0 in LLVMFuzzerTestOneInput coturn/fuzz/FuzzStun.c:37:5
#4 0x43ede3 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
#5 0x42a542 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:324:6
#6 0x42fdec in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, …
```
=> Fix : Issue 51563 in oss-fuzz

src/apps/common/hiredis_libevent2.c, src/apps/relay/dbdrivers/dbd_redis.c
Hello,
while using the `redis-statsdb` option, I found that coturn is leaking sockets (and memory) in case of redis reconnection.
This occurs a lot to me, because in my setup I have a `coturn -> haproxy -> redis` and if all my redis servers are down, HaProxy abruptly close the connection to coturn and coturn reconnects periodically. After some time I can see thousands of pending sockets (`CLOSE_WAIT`) :
```
user@server[11:32:48 UTC]:~$ sudo lsof -i | grep turn
turnserve 461797       root   15u  IPv4 12856075      0t0  TCP server:3478 (LISTEN)
turnserve 461797       root   22u  IPv4 12856081      0t0  TCP server:3478 (LISTEN)
turnserve 461797       root   23u  IPv4 12857384      0t0  UDP server:3478 
turnserve 461797       root   24u  IPv4 12857385      0t0  UDP server:3478 
turnserve …
```
=>  Redis memleaks and socketleaks

configure, src/apps/relay/CMakeLists.txt, src/apps/relay/tls_listener.c
turnserver includes support for SCTP and tries to initialize listener sockets with SCTP protocol. On machines where SCTP definitions exist but the protocol is not provided - socket() returns error which shows up as `socket: protocol not supported`
This change improves a few related pieces of code:
- Log error instead of perror
- config script detect sctp.h and if not present - defines TURN_NO_SCTP
- CMake fully disables SCTP (for now - requires custom module to detect SCTP presence)
Fixes #492
=> Better detect SCTP protocol

src/apps/relay/dbdrivers/dbd_mysql.c, src/apps/relay/dbdrivers/dbd_pgsql.c, src/apps/relay/dbdrivers/dbd_redis.c, src/apps/relay/dbdrivers/dbd_sqlite.c, src/apps/relay/dbdrivers/dbdriver.c, src/apps/relay/dbdrivers/dbdriver.h, src/apps/relay/mainrelay.c, src/apps/relay/mainrelay.h, src/apps/relay/netengine.c, src/apps/relay/ns_ioalib_engine_impl.c, src/apps/relay/ns_ioalib_impl.h, src/apps/relay/turn_admin_server.c, src/apps/relay/userdb.h
Store sanitized version of DB connection string with password masked (replace all chars with * which exposes its length)
Use sanitized version when logging connection string
Fixes #1017 and #272
=> Sanitize DB connection string before printing to log

src/apps/relay/ns_ioalib_engine_impl.c
-extra verbose has int value of 2, ensure it's not lost when calling ssl_read and ssl_send
=> fix bug in calls to ssl_read and ssl_send where extra verbose flag goes missing

src/apps/relay/mainrelay.c
Rewriting openssl initialization code (threading support to make it cleaner
- Regroup functions so that there is one ifdef (for old code and new code)
- Modern openssl (>1.0.2) does not need any synchornization routines so they are empty
- Old openssl (<=1.0.2) now require `OPENSSL_THREADS` which allows running multiple threads in turnserver. Not having turnserver multi-threaded is a huge waste. `OPENSSL_THREADS` is now a requirement.
Test Plan:
- CI builds pass for openssl versions 1.0.2, 1.1.1, 3.0, including tests
=> Cleanup openssl initialization

src/apps/oauth/oauth.c
The `gcm_nonce` character array is `12 + 1` chars long. Writing to `gcm_nonce[12 + 1]` overflows the array by one char.
=> Fix off-by-one when terminating gcm_nonce

rpm/turnserver.service.fc
Fix the issue https://github.com/coturn/coturn/issues/118 that prevent the process to start as coturn never send the notification to systemd thus preventing the startup.
Cherry-picked from #990 thanks to @rapsys
=> Change rpm systemd service type from notify to exec

src/apps/relay/ns_ioalib_engine_impl.c, src/apps/relay/ns_ioalib_impl.h
Modify SSL backlog buffer from LIFO to queue/FIFO
If data ends up in the ssl_backlog_buffer because we are waiting for a handshake to finish, then this change ensures that the data is sent out in the proper order once the handshake completes.  Previous code was sending in LIFO order.
=> Backlog fifo

src/apps/common/apputils.c, src/apps/common/apputils.h
Function with no arguments must be defined as f(void) according to C standard
=> Fix compilation warnings for functions with no arguments

src/apps/common/ns_turn_utils.h
Remove unnecessary declaration.
The implementation of the vrtpprintf function has been removed in commit 5e87c444693b39e11cabc498450dacbef30ec64a.
=> Remove unnecessary declaration from header file

src/apps/relay/CMakeLists.txt, src/apps/relay/mainrelay.c, src/apps/relay/mainrelay.h, src/apps/relay/ns_ioalib_engine_impl.c, src/apps/relay/prom_server.c, src/apps/relay/prom_server.h
`TURN_NO_PROMETHEUS` is defined when prometheus libraries are not present and any prometheus functionality must be disabled
While all above is correct, it does not require ifdef-ing out all related code.
For example, prometheus related fields in turn_params do not need to be compiled out. Same for certain function parameters.
This PR reduces amount of places in code where `TURN_NO_PROMETHEUS` is used to make code simpler by moving as much usage of this define into prom_server.h/c files and compiling them unconditionally.
- Always compile/link prom_server.c
- Move many TURN_NO_PROMETHEUS decisions into prom_server.c
=> Reduce usage of TURN_NO_PROMETHEUS

src/apps/natdiscovery/natdiscovery.c, src/apps/oauth/oauth.c, src/apps/peer/mainudpserver.c, src/apps/rfc5769/rfc5769check.c, src/apps/stunclient/stunclient.c, src/apps/uclient/mainuclient.c
Disables default log output to stdout if stdout is set as logfile.
When execute `turnutils_stunclient` , the output will be duplicated as in the following example.
```
$ ./turnutils_stunclient stun.example.com
0: : IPv4. UDP reflexive addr: 203.0.113.1:10000
0: : IPv4. UDP reflexive addr: 203.0.113.1:10000
```
This is because stdout is set in `set_logfile` and furthermore log output to stdout is done by default.
In this change, call `set_no_stdout_log` to disable default log output to stdout when stdout is set as logfile.
This solves the problem of duplicate output to stdout of the same log.
=> Update to fix duplicate stdout log output

src/apps/common/CMakeLists.txt, src/apps/common/apputils.c, src/apps/relay/CMakeLists.txt, src/apps/relay/mainrelay.c, src/ns_turn_defs.h, src/server/ns_turn_maps.h
On LLP64 systems (read Windows) unsigned long is only 4 bytes wide, which makes it very unsuitable for storing pointers.
-----
Additional comments:
uintptr_t since c99 or uintptr_t since C++11
see: https://cplusplus.com/reference/cstdint/, https://en.cppreference.com/w/c/types/integer, https://en.cppreference.com/w/cpp/types/integer
C11 re-enabled in #1056
=> WINDOWS: unsigned long should not be used to store pointers

src/apps/oauth/oauth.c
Warning emitted from GCC:
```
warning: passing argument 1 of ‘free’ discards ‘const’ qualifier from pointer target type
```
=> Do not discard qualifiers in free()

src/apps/relay/ns_ioalib_engine_impl.c
The `sm_allocated` field is an array of `size_t` values. Therefore its size must be calculated as `n * sizeof(size_t)`.
Our static code analysis tool complained:
```
Sizeof not portable (SIZEOF_MISMATCH)
suspicious_sizeof: Passing argument r->sm_allocated of type size_t * and argument (r->sm_chunk + 1) * 8UL /* sizeof (size_t *) */ to function realloc is suspicious. In this case, sizeof (size_t *) is equal to sizeof (size_t), but this is not a portable assumption.
```
Fix: #1045
=> Properly calculate size for sm_allocated

src/apps/relay/libtelnet.c
The MSVC CI pipelines broke in #1056 due to the bump in C standard version.
=> Repair MSVC CI builds

src/apps/uclient/mainuclient.c, src/client/ns_turn_msg.c
Use version independent APIs for openssl-1.1.0 and above
Tested with turnutils_uclient against a turnserver with TLS and DTLS modes
=> Update openssl API use to non-deprecated version

.github/workflows/macos.yml
Fixes #1051 
This adds basic PR build action on macOS to confirm we keep builds green for developers using mac
=> Add macOS build action

src/apps/relay/prom_server.c
Prometheus would aggregate across all labels (when not specifying)
In this scenario `turn_total_allocations` does not need separate label "type=all" as such in this case the result would be double the actual amount
=> Fix duplicate prometheus metric report

CMakeLists.txt, src/ns_turn_defs.h
Example usage with make:
make CPPFLAGS="-DTURN_SERVER_BUILD_INFO=\"\\\" git: $(git rev-parse HEAD) build: 123\\\"\""
Example usage with cmake:
cmake .. -DTURN_SERVER_BUILD_INFO="\" git: $(git rev-parse HEAD) build: 123\""
=> Optional build info compiled into turnserver binary

src/apps/common/apputils.c, src/apps/common/apputils.h, src/apps/common/win/getopt.h, src/apps/relay/mainrelay.c, src/apps/relay/netengine.c, src/apps/relay/ns_ioalib_engine_impl.c, src/apps/relay/turn_admin_server.c, src/server/ns_turn_server.c
Reformatting and removing some duplications:
- Some lines have WARNING WARNING: cleaned up.
- Lines printed using perror: only LOG_ mechanism should be used.
- Printing IO mechanism (epoll for example) for each thread: selected mechanism logged once
- Duplicate lines (perror and also LOG): duplication removed
- Duplicates: clean up (because calling function multiple times - configuration load)
=> Cleanup logs on turnserver start

.github/workflows/docker.yml, docker/coturn/.gitignore, docker/coturn/CHANGELOG.md, docker/coturn/CONTRIBUTING.md, docker/coturn/Makefile, docker/coturn/README.md, docker/coturn/package.json, docker/coturn/tests/main.bats
This PR reworks Docker image toolchain to allow separate granular CI builds per arch. This speeds up Docker CI, provides cheaper retries, and allows finding regressions more precisely.
Additionally:
- improves test to show failed output
- removes usage of deprecated GitHub Actions features
=> Granular Docker CI

src/apps/relay/ns_ioalib_engine_impl.c
Fix memory corruption introduced by commit c8663f4a91cd2d88f1d0e65144158c7bcfe8b35c
If there was an unsuccessful session registration in open_client_connection_session, it adds a timer (before it didn't).
Later during runtime, at session destruction, it removes the client_socket in close_ioa_socket. Then the timer gets triggered and runs the cleanup method client_to_be_allocated_timeout_handler and tries to access the stored client_socket. This then fails as it already was freed.
The fix just sets the client_socket pointer to null and then the timer should detect this and not access already freed memory.
The issue affects version 4.6.0, 4.6.0-r0 and 4.6.0-r1.
=> Fix memory corruption on socket close

src/apps/relay/mainrelay.c
This PR fixes some errata from #996 and #989:
- Some DTLS code was left over in the common path for allocating and initialising `SSL_CTX`'s, and the DTLS-specific configuration code was erroneously operating on the TLS context instead of the DTLS context.
- In both the TLS and DTLS codepaths, the previous refactoring inverted the logic for the `--no-tlsv1`/`--no-tlsv1_1`/etc command line options, so that these options would instead *enable* the respective (D)TLS versions, instead of disabling this. This would mean that by default coturn would only support TLS 1.3 and DTLS 1.2, and no earlier versions.
I've also regenerated the manual pages (with the `make-man.sh` script) to match the documentation in the README files.
=> Fix inverted logic in TLS configuration options

README.turnadmin, README.turnserver, README.turnutils, man/man1/turnadmin.1, man/man1/turnserver.1, man/man1/turnutils.1
This PR fixes some typos and formatting, and regenerates the manual pages from the README files. These changes were originally included in #1105, however I've split them out into a separate PR as requested.
=> Regenerate manual pages from README files

src/apps/relay/mainrelay.c
coturn running inside a docker container runs as PID 1, however PID 1 has special signal handling semantics (see the note at the bottom of the section [here](https://docs.docker.com/engine/reference/run/#foreground)). coturn relies on the default behaviour of SIGTERM to terminate the process, however as no signal handler is explicitly installed, it doesn't respond to SIGTERM when running inside a container. This PR fixes this problem by installing explicit signal handlers for SIGINT and SIGTERM, which trigger the same termination mechanism as the admin interface "halt" command.
This is a port of wireapp#6 for upstream.
=> Add explicit SIGTERM and SIGINT handlers.

src/apps/relay/prom_server.c
It's not working when constructing it in-place, likely this is undefined behaviour.
=> bugfix: fix broken type label of turn_total_allocations gauge

src/apps/relay/prom_server.c
This should result in a address of temporary array.
=> Fix wrong usage of C-sytle in place generated array

src/apps/common/apputils.c, src/apps/common/hiredis_libevent2.c, src/apps/natdiscovery/natdiscovery.c, src/apps/peer/udpserver.c, src/apps/relay/dtls_listener.c, src/apps/relay/netengine.c, src/apps/relay/ns_ioalib_engine_impl.c, src/apps/relay/tls_listener.c, src/apps/relay/turn_admin_server.c, src/apps/stunclient/stunclient.c, src/apps/uclient/startuclient.c, src/apps/uclient/uclient.c, src/ns_turn_defs.h
Since winsock do not use errno, and have different error codes, this is needed to be windows compatible
This pull request is a split of PR #1061
=> Use inline functions for errno checks

src/apps/relay/dtls_listener.c
This pull request is a split of PR #1061
As @KangLin pointed out in the original PR those sockets should ideally be permanently non-blocking for performance reasons, but they are NOT at the moment.
Someone with more knowledge about the code in dtls_listener.c should probably have a look if it would be feasible to change the sockets to non-blocking already at creation, similar to what is done in udpserver.c...
=> Implement non-blocking recvfrom on Windows

.github/workflows/macos.yml
MacOS CI build started to fail in the PRs because when upgrading python it was not possible to override one existing file (related to 2to3 package).    Apparently this happens because MacOS runners some times have python versions not installed/compatible with brew.
Example of the failure: https://github.com/coturn/coturn/actions/runs/3850951324
The proposed workaround is taken from here: https://github.com/actions/runner-images/issues/2322
=> Fix brew for MacOS CI build

src/apps/relay/dbdrivers/dbd_redis.c
=> Use the actual redis connection string to connect, not the sanitized one

src/apps/relay/dbdrivers/dbd_pgsql.c
Noticed the plaintext password of my postgresql server in my coturn logs, but postgresql errors would return the password sanitised. Simple fix to log the sanitised string.
Signed-off-by: r3g_5z <june@girlboss.ceo>
=> use santisied psql string

src/apps/common/apputils.c
PR #855 introduced new include <ssys/sysinfo.h> 
It is not required for compilation or turnserver function but breaks OpenBSD build (which does not have this file)
This PR removes the include to restore OpenBSD build compatibility
Fixes #1162
Test Plan:
TBD - need some one to test build
=> Remove unused include that breaks OpenBSD

src/ns_turn_defs.h
Removing windows.h inclusion, not needed with ws2tcpip.h. Causes some struct redefinitions.
=> Fix MSVC CI build

docker/coturn/CHANGELOG.md, docker/coturn/CONTRIBUTING.md, docker/coturn/Makefile, docker/coturn/README.md
Resolves #1226
Adds additional Docker tags with concrete OS versions (`alpine3.18`/`bookworm`).
=> Improve Docker tagging by tracking OS version (#1226)

src/apps/common/ns_turn_utils.c
Environment:
- Windows 10
- Cygwin 2.925
make output:
```
<command-line>: note: this is the location of the previous definition
src/apps/common/ns_turn_utils.c:53:10: fatal error: sys/syscall.h: No such file or directory
53 | #include <sys/syscall.h>
|          ^~~~~~~~~~~~~~~
compilation terminated.
In file included from src/client/ns_turn_ioaddr.h:34,
from src/client/ns_turn_msg.h:34,
from src/apps/common/stun_buffer.h:34,
from src/apps/common/stun_buffer.c:31:
src/ns_turn_defs.h:223: warning: "TURN_NO_SCTP" redefined
223 | #define TURN_NO_SCTP
|
<command-line>: note: this is the location of the previous definition
make: *** [Makefile:127: bin/turnutils_oauth] Error 1
```
=> Fix error of make command in Cygwin environment

README.md, README.turnserver, examples/etc/turnserver.conf
added some warnings that the prometheus implementation is unavailable when installing through apt
coturn/coturn#1133
=> added warnings for prometheus apt unavailability

docker/coturn/turnserver.conf, examples/etc/turnserver.conf, src/apps/relay/mainrelay.c
Fixes https://github.com/coturn/coturn/issues/1239
https to web ui freeze in browser if no_tls option used, because no tls stuff initialized.
This PR add warning about this and comment aboute this in default config
=> Add warning and disable web admin if no-tls option used

src/apps/common/ns_turn_utils.h, src/client/ns_turn_msg.c, src/server/ns_turn_server.c
Add missing checks for length of realm/nonce/server_name before copying those values to the buffer passed to stun_is_challenge_response_str.
The function stun_is_challenge_response_str is only used in uclient test application.
Thank you very much @0xdea
=> Fix memcpy len checks stun_is_challenge_response_str

src/apps/common/apputils.c, src/apps/common/apputils.h, src/apps/relay/mainrelay.c, src/client/ns_turn_msg.c
- srandom/random provide stronger randomness characteristics than srand/rand in some operating systems.
- usage of srand/rand is not very consistent in coturn.
There is room for more refactoring and use apputils helper functions in ns_turn_msg.c too but i'm not sure that dependency from "client" module to "apps" module is a good idea yet.
Thx @0xdea
=> Replace srand/rand with srandom/random

src/apps/relay/dbdrivers/dbd_pgsql.c
Fixes #1259
If `ur_string_map_put ` fails then the string that was just `strdup`-ed will leak memory 
Now the return value is checked and memory free-ed in case of failure
=> Fix memleak in pgsql_reread_realms

.github/workflows/tests.yml
Builds started to fail in ubuntu 16.04: https://github.com/coturn/coturn/actions/runs/6368822745/job/17288499081?pr=1280
It is apparently related to the glib version using by node: https://github.com/actions/checkout/issues/1474
The simplest solution I found is to use checkout@v3 that I think should be fine given that we only need to use it to download the repo code.
=> Fix ubuntu 16 build with GH action checkout version to v3

src/client/ns_turn_msg.c
Add missing null termination for string composed at fix_stun_check_message_integrity_str.
The function fix_stun_check_message_integrity_str is only used in uclient and rfc5769check test applications.
Thx @0xdea
=> Fix missing strncpy in fix_stun_check_message_integrity_str

examples/etc/turnserver.conf, src/apps/relay/mainrelay.c, src/apps/relay/mainrelay.h, src/apps/relay/netengine.c, src/server/ns_turn_server.c, src/server/ns_turn_server.h
For our deployment, it is useful if coturn returns a valid HTTP response to an HTTP request. To do this on the same port as STUN/TURN and without enabling the admin site, I have extended `read_client_connection()` to return a canned HTTP response, in response to an HTTP request, rather than immediately closing the connection.
=> Return a 400 response to HTTP requests

src/server/ns_turn_server.c
Fixes #1266 
According to RFC 5766, [section 6.2](https://www.rfc-editor.org/rfc/rfc5766#section-6.2) point no. 5, the turn server needs to reject the request with 508 (Insufficient Capacity) error code when the given RESERVATION-TOKEN is not valid.
=> Fix: Return correct error code for `create_relay_connection` in case of `RESERVATION-TOKEN` failure

CMakeLists.txt
BUILD_TEST is not implemented in CMakeLists.txt
Removing to prefent confusion
Fixes #1367
=> Remove unimplemented test folder reference from CMakeLists.txt

src/apps/relay/prom_server.c, src/apps/relay/prom_server.h
If IPv6 is not enabled during runtime, prometheus server fails to start with `EAFNOSUPPORT` because `MHD_USE_DUAL_STACK` is set unconditionally.
This PR fixes it. As a bonus, it also checks if libmicrohttpd is compiled with IPv6 support.
=> Only set MHD_USE_DUAL_STACK if IPv6 is available

src/apps/common/ns_turn_utils.c, src/apps/relay/dbdrivers/dbd_sqlite.c, src/apps/relay/mainrelay.h, src/ns_turn_defs.h
As mentioned in multiple source, `__APPLE__` is enough to detect macOS (or iOS but since we do not target it then we ignore it). 
https://github.com/cpredef/predef/blob/master/OperatingSystems.md#macos
Tested by building on macOS - no difference observed
=> Simplify macOS detection macros

src/server/ns_turn_server.c
Added session id parameter to use it in "A peer IP <IP> denied in the range" logs. Besides, server ID has been made visible in this logs.
=> Missing session ID in coturn logs for denied IP - 1330

src/server/ns_turn_server.c
Some events are missed when logs are filtered by session ID. That's why I added the sessionID to some log lines.
=> Added sessionID to some log lines

src/client/ns_turn_msg.h
trivial - cmake generated a warning that `ns_turn_msg.c` used a function that had no prior prototype - most other files used the `turn_random()` function but this uses `turn_random_number()` which has no prototype, so i've added it to the header file
=> added missing function prototype of turn_random_number()

src/apps/natdiscovery/natdiscovery.c, src/apps/stunclient/stunclient.c
- if a variable of type `int` was only being used as a boolean, replace it with bool as defined in `<stdbool.h>`
- replace its declaration and assignment with true/false, depending on prior assignment as 0/1
changes were only made when i was certain the variables were not being used as an int, so i may have missed some
---
- `rfc5780`
- `change_ip`
- `change_port`
their usages were changed only where they appeared in the apps directory, and then everywhere that generated a warning after make
- `stunclient.c` itself
- `natdiscovery.c`
=> changed variables in stunclient.c to bool (C11)

src/apps/relay/http_server.c
This is in response to issue #1365.
The clang static analyzer basically claims that there is a memory leak happening in `parse_http_request_1` for the variable `kv`. The leak is triggered when evhttp_parse_query_str fails and is unable to obtain key value pairs for a given URI. In this case ret is freed, however kv is still not freed and thereafter not used. Therefore as a patch I am freeing kv right after ret is freed.
Please let me know if this patch is helpful :)
=> Fix memory leak on http_server.c

src/apps/relay/netengine.c
This is in response to issue #1366
The clang static analyzer basically claims that there is a memory leak happening in `set_ssl_ctx` for the variable `args`. The leak is  triggered when the base event `base` is NULL and the condition within `set_ssl_ctx` is not triggered. Therefore as a patch I am adding an else condition to free it. (It cannot be freed after the event is created by `event_new` because `args` can be invoked as argument for callback function later on)
Please let me know if this patch is helpful :)
=> Fix memory leak in netengine.c

src/apps/rfc5769/rfc5769check.c
I came across the open issue #1368 which is a leaksanitizer report about a leak that happens on make check. I was able to reproduce the bug on running `make check` and was able to generate a patch for it. The leak happens within function `check_oauth`. 
Issue: The variable `base64encoded_ltp` is allocated within `base64_encode` however it is not de-allocated within the coming loop.
I have verified that after the patch, the leak no longer occurs through `leaksanitizer` (and there is no double free for that matter)
=> Fix memory leak in rfc5769check.c

src/client/ns_turn_msg.c
before this change i see a bufferflow during `readable_string`.
=> generate_enc_password: increase rsalt by 2

src/apps/rfc5769/rfc5769check.c
rfc5769check.c file is using ERROR as a label for gotos but apparently that name is already used for a constant and msvc analyzer detects it as an error.     
Rename it to "err" that is already used in other parts of the codebase and also more consistent in terms of casing.
=> Fix msvc analyzer error on goto label on rfc5769check

.github/workflows/lint.yml
Someone working on a branch in their own fork won't see the lint running on their github-actions CI until they open a pull request.
It'd be much easier to ensure changes being worked on are going to pass the linter if the linter runs before the last step of opening the PR.
=> Always run lint, regardless of branch

src/client/ns_turn_msg.c
The value `0x5354554e`, used twice in the `ns_turn_msg.c`, was unclear, and was changed to a macro that better explained its usage, as defined in [RFC 5389](https://datatracker.ietf.org/doc/html/rfc5389#section-15.5)
=> defined a magic number for stun fingerprinting

src/apps/relay/mainrelay.c
The code used `get_system_number_of_cpus()` instead of `get_system_active_number_of_cpus()` to configure number of relay servers.
That caused incorrect number to be used on virtualized systems. See #1468
=> Use active CPU number instead of total number

src/server/ns_turn_maps.c, src/server/ns_turn_maps_rtcp.c, src/server/ns_turn_server.c
#1502 made APIs consistent with using bool as a return value where true is success and false is failure
In a few places the change broke code
This PR fixes the breakage
=> Address some build issues introduced by api changes

.github/workflows/codeql.yml
I'm having trouble testing changes in my own fork because many of the CI workflows are only set to build on a pull request.
Better to just build on any commit.
I've left the docker builds as they are.
=> Run all of the CI except for Docker builds on any change

src/apps/relay/dbdrivers/dbd_mysql.c, src/apps/relay/userdb.c
addresses a code scanner vulnerability
the combination of `strlen` and `malloc` results in space being allocated for the string, but not the null terminator required to end the string, so space for an extra character has to be manually specified
- CERT C Coding Standard: [MEM35-C. Allocate sufficient memory for an object](https://www.securecoding.cert.org/confluence/display/c/MEM35-C.+Allocate+sufficient+memory+for+an+object).
- Common Weakness Enumeration: [CWE-131](https://cwe.mitre.org/data/definitions/131.html).
- Common Weakness Enumeration: [CWE-120](https://cwe.mitre.org/data/definitions/120.html).
- Common Weakness Enumeration: [CWE-122](https://cwe.mitre.org/data/definitions/122.html).
=> malloc now allocates space for string terminator

src/apps/relay/dbdrivers/dbd_mongo.c, src/apps/relay/dbdrivers/dbd_mysql.c, src/apps/relay/dbdrivers/dbd_pgsql.c, src/apps/relay/dbdrivers/dbd_redis.c, src/apps/relay/dbdrivers/dbd_sqlite.c, src/apps/relay/dbdrivers/dbdriver.c, src/apps/relay/dbdrivers/dbdriver.h, src/apps/relay/userdb.c, src/ns_turn_defs.h
The general approach here was:
- Always declare variables as close to where they are defined as possible.
- Check for pre-conditions of functions before doing work (e.g. ensure we can connect to the DB before doing a bunch of string formatting)
- Keep the scope of mutexes as reasonably small as practical.
- Use idiomatic C11, such as for-loops over the thing being iterated, not while() loops over constants, or variables that aren't modified.
- Prefer if(fail){return} function-body after over `if(not fail){ function-body inside if} return;
Clang-tidy returns a clean bill of health, but while going through this file i noticed a lot of things that raise questions.
Lack of checking column counts. Lack of handling the possibility of multiple return values. Questionably handling of strings. …
=> Address clang-tidy warnings in db files

.github/workflows/amazon_linux_tests.yml, .github/workflows/tests.yml, .github/workflows/ubuntu_tests.yml
superseding changes made in pr https://github.com/coturn/coturn/pull/1394 on request of @jonesmz
dependent on pr https://github.com/coturn/coturn/pull/1399 - uses the composite action for dependency installation i wrote there
added YAML file for amazon linux and renames tests.yml to ubuntu_tests.yml for clarity
=> added support for amazon linux and renamed tests.yml

.github/workflows/amazon_linux_tests.yml, .github/workflows/cmake.yaml, .github/workflows/compiler-sanitizers.yml, .github/workflows/macos.yml, .github/workflows/ubuntu_tests.yml, examples/run_tests_conf.sh, src/apps/relay/mainrelay.c
Fixes #1533 and #1534
Memsetting `turn_params.default_users_db` before reading conf file, not after.
Because auth is read in first iteration so secret was wiped out.
Add new test script that uses config file to setup turnserver instead of cli arguments and confirm it works (fails without the change)
=> Memset user_db before reading conf file, not after

src/apps/relay/mainrelay.c
Previously if the system had an interface with a static IP configured, coturn would attempt to bind to that address, even if the interface was down. This would fail, and prevent coturn from starting (even if there were other usable interfaces)
=> windows: Only attempt to bind when the network interface is up

.github/workflows/amazon_linux_tests.yml, .github/workflows/ubuntu_tests.yml
This problem is caused by this issue: https://github.com/actions/checkout/issues/1809
Several comments include documentation on various environment variables to force it to use the older nodejs release still, but probably those various workarounds will stop working eventually.
=> Fix nodejs/glibc problem with old container images.

src/apps/relay/dtls_listener.c, src/apps/relay/hiredis_libevent2.c, src/apps/relay/netengine.c, src/apps/relay/ns_ioalib_engine_impl.c, src/apps/relay/turn_admin_server.c, src/apps/relay/userdb.c, src/apps/uclient/uclient.c, src/ns_turn_defs.h, src/server/ns_turn_allocation.c, src/server/ns_turn_maps_rtcp.c, src/server/ns_turn_server.c
Almost all of the warnings were about truncating pointers, because sizeof(void*) != sizeof(long) on all platforms.
=> Fix compiler warnings from continuous integration

configure
for example it creates `/etc/turnserver.conf.default` as executable, which is strange...
=> configure: data files shouldn't be executable

src/apps/relay/turn_admin_server.c
Fix to avoid accept all password except the right cli_password
=> Fix cli auth

src/apps/relay/netengine.c, src/server/ns_turn_server.c, src/server/ns_turn_server.h
`stun_port` isn't read after setting it. Thus, we can remove it.
=> Delete dead code

src/apps/relay/mainrelay.c
fixed a formatting problem causing issues with `clang-format` in the linting action
see [here](https://github.com/redraincatching/coturn/actions/runs/10262259860) for an example
=> fixed linting error in mainrelay.c

src/client++/TurnMsgLib.h, src/server/ns_turn_allocation.c, src/server/ns_turn_allocation.h
You can see the list here: https://github.com/coturn/coturn/security/code-scanning
In this case, i'm attempting to address:
ns_turn_allocation.c:725 -- Dereferencing NULL pointer. 'ub->bufs' contains the same NULL value as 'realloc()' did.
ns_turn_allocation.c:724 -- 'realloc' might return null pointer: assigning null pointer to 'ub->bufs', which is passed as an argument to 'realloc', will cause the original memory block to be leaked.
ns_turn_allocation.c:604 -- Dereferencing NULL pointer. 'a->tcs.elems' contains the same NULL value as 'realloc()' did.
ns_turn_allocation.c:582 -- Dereferencing NULL pointer 'tc'.
ns_turn_allocation.c:603 -- 'realloc' might return null pointer: assigning null pointer to 'a->tcs.elems', which is passed as an argument to 'realloc', will cause the original …
=> Additional refactoring of ns_turn_allocation.* to address security scanner concerns

.github/workflows/amazon_linux2023_tests.yml, .github/workflows/amazon_linux2_tests.yml, .github/workflows/amazon_linux_tests.yml
In preparation to deprecation of openssl below version 1.1.1 switch to using openssl-1.1.1 on amazonlinux:2 (where 1.0.2 is the default)
Fixes build issue for #1397
=> Install openssl-1.1.1 on amazonlinux:2 instead of openssl-1.0.1

examples/etc/turnserver.conf
I believe that many users, like myself, prefer to reference the `turn.conf` file when deploying the TURN server with Docker, rather than the `Readme.turnserver`. Additionally, I think it's important to synchronize the Prometheus settings from the README into the` turn.conf` file for better clarity. This way, users won't overlook any essential options.
=> Add prometheus setting suggestions on turn.conf in example folder

src/apps/relay/dbdrivers/dbd_redis.c, src/apps/relay/hiredis_libevent2.c, src/apps/relay/hiredis_libevent2.h, src/apps/relay/mainrelay.c
I needed this
I just looked for occurrences of password and added username branches there. Let me know if there's anything wrong, I'm not proficient in C at all.
=> Allow authenticating with a username to redis

.github/workflows/actions/ubuntu-build-deps/action.yml, .github/workflows/amazon_linux2023_tests.yml, .github/workflows/amazon_linux2_tests.yml, .github/workflows/cmake.yaml, .github/workflows/compiler-sanitizers.yml, .github/workflows/macos.yml, .github/workflows/mingw.yml, .github/workflows/ubuntu_tests.yml, cmake/FindPrometheus.cmake, configure, docker/coturn/alpine/Dockerfile, docker/coturn/debian/Dockerfile, examples/run_tests_prom.sh, src/apps/relay/CMakeLists.txt, src/apps/relay/mainrelay.c, src/apps/relay/mainrelay.h, src/apps/relay/prom_server.c, src/apps/relay/prom_server.h
Implement a custom prometheus http handler in order to:
1. Support listening on a specified address as opposed to any
2. Remove the requirement on the unmaintained promhttp library
This feature comes with one limitation: if an IPv4 address is used, the server will not listen on the IPv6-mapped address, even if IPv6 is available. That is, dual-stacking does not work.
Solves: #1475
=> Implement custom prometheus http handler

.github/workflows/amazon_linux2023_tests.yml, .github/workflows/cmake.yaml, .github/workflows/macos.yml, examples/run_tests.sh, examples/run_tests_conf.sh, examples/run_tests_prom.sh
Some actions do not build with prometheus - adding prometheus tests fails the jobs
cmake build tests did not run due to different target folder (while reporting success) - now the bin folder is detected
=> Fix cmake and prometheus test build jobs 

src/apps/common/apputils.h, src/apps/relay/mainrelay.c, src/apps/uclient/startuclient.c
As of openssl 1.1.1 ALPN is supported - no need for all the ifdefs anymore
=> Cleanup ALPN_SUPPORTED define usage

src/apps/common/apputils.c
Every time the '_WTA' is called, its initial value is null, so the function returns directly.
https://github.com/coturn/coturn/blob/c98bb935148288b6d13a8b954422a52edfb17a83/src/apps/common/apputils.c#L905-L908
https://github.com/coturn/coturn/blob/c98bb935148288b6d13a8b954422a52edfb17a83/src/apps/common/apputils.c#L939-L941
https://github.com/coturn/coturn/blob/c98bb935148288b6d13a8b954422a52edfb17a83/src/apps/common/apputils.c#L960-L962
https://github.com/coturn/coturn/blob/c98bb935148288b6d13a8b954422a52edfb17a83/src/apps/common/apputils.c#L981-L983
=> Windows '_WTA' bug

src/apps/relay/mainrelay.c, src/apps/relay/mainrelay.h, src/apps/relay/turn_admin_server.c, src/server/ns_turn_server.c, src/server/ns_turn_server.h
approach was as follows, for the `_turn_params_` struct:
- if a variable of type `int` or `vint` was only being used as a boolean, replace it with bool as defined in `<stdbool.h>`
- replace its declaration with true/false, depending on prior assignment as 0/1
changes were only made when i was certain the variables were not being used as an `int`, so i may have missed some
no changes were made to other sections of the code as int-to-bool assignment is allowed in C, only code within the structs were changed, but that can be changed with a later commit
---
from a documentation perspective, it's not clear as to what purpose or benefit the vint alias has. the definition in `ns_turn_defs.h` simply reads
```c
typedef int vint;
typedef vint *vintp;
```
with no comments, and it seems most (but not …
=> updated types to bool in _turn_params_ to reflect C11

examples/etc/turnserver.conf
The `#allocation-default-address-family="ipv4"` line is repeated twice in the example config, changed the second one to be `"ipv6"` which I assume it was intended to be.
=> [Quick Fix] Fix Repeated Line in Example turnserver.conf

src/apps/relay/userdb.c
Fix #1657 
This log was added in a recent refactor for draining support and it is very noisy.   With this change the log is moved behind the "verbose" flag and also does a minor cleanup to not have 2 duplicated lines for logging when one is enough.
=> Show allocations increment/decrement logs behind verbose flag

src/apps/relay/prom_server.c
Restore the support to return a 200 OK in the root prometheus endpoint (/) as stated in the documentation.
This feature was lost when removing libpromhttp
Fixes #1672
=> Restore returning 200 OK on root prometheus path for health check

src/apps/common/ns_turn_utils.c, src/apps/common/ns_turn_utils.h, src/apps/relay/prom_server.h, src/client/ns_turn_msg.c
This adjusts the code to allow compilation with a C++ compiler, but doesn't change the build to use a C++ compiler. Everything should continue working as-is with existing c-compilers. This is just a "let it work" change, not a "change how it works" change.
=> Fix the ability to compile coturn using C++ compiler

src/apps/relay/libtelnet.c
When building with default configuration at least in MacOS we get warnings about those conversions from const char* to char*.   Fix it by making all those argv ""const char*"
=> Fix compilation warning with const - non const conversions

docs/Developer.md
Add basic diagram with modules of coturn inside Developer.md.
I also wanted to move the existing Flow chart to mermaid so that our doc doesn't depend on external tools but i couldn't find the time to do it properly (horizontal arrows are hard to represent with mermaid) so i postponed that part.
This is the result of the mermaid diagram:
=> Add modules diagram to developer doc

README.turnserver, docker/coturn/turnserver.conf, examples/etc/turnserver.conf, man/man1/turnserver.1, src/apps/relay/mainrelay.c, src/apps/relay/netengine.c
Invert `--no-rfc5780` option to be true by default
Make it `--rfc5780` to enable it
Update example/recommended configuration files
Passing `--no-rfc5780` will have no effect as this is the default behavior now
=> Invert RFC5780 option to default off

README.turnserver, docker/coturn/turnserver.conf, examples/etc/turnserver.conf, src/apps/relay/mainrelay.c, src/apps/relay/mainrelay.h, src/apps/relay/netengine.c, src/server/ns_turn_server.c, src/server/ns_turn_server.h
Make this true - response-origin-only will only be enabled with rfc5780 option on
=> [BREAKING] Deprecate response-origin-only-with-rfc5780

docker/coturn/CHANGELOG.md, src/server/ns_turn_server.c
Fixes [#1071](https://github.com/coturn/coturn/issues/1071)
Not sure how this case can happen but better to handle the error case.
=> Add missing close socket when ioa_socket call fails

examples/etc/turnserver.conf, man/man1/turnserver.1, src/apps/common/apputils.h, src/apps/relay/mainrelay.c, src/apps/relay/mainrelay.h, src/apps/relay/ns_ioalib_engine_impl.c, src/apps/relay/turn_admin_server.c
TLSv1 and TLSv1.1 can be enabled using `--tlsv1` and `--tlsv1_1` arguments accordingly
That assumes openssl version being used has these versions enabled (which as of openssl-3.5 is not by default)
=> Make older TLS versions optional

CMakeLists.txt, ChangeLog, examples/scripts/pack.sh, release.sh, rpm/build.settings.sh, rpm/turnserver.spec, scripts/install_coturn_on_aws_ec2.sh, src/apps/relay/mainrelay.c, src/client++/TurnMsgLib.h, src/client/ns_turn_msg_defs.h, src/ns_turn_defs.h, src/server/ns_turn_server.c, vcpkg.json
Set new release version to 4.7.0
Updating minor version due to some breaking changes in options to enable more secure/robust configuration without additional flags (or relying on recommended conf file which people seem to skip during updates)
=> Update version to 4.7.0

docker/coturn/turnserver.conf
Following the comments, verbose mode should be commented out by default.
=> fix: comment out verbose mode by default

src/apps/relay/ns_ioalib_engine_impl.c, src/server/ns_turn_maps_rtcp.h
removing an unnecessary null check as raised in [this code scan](https://github.com/redraincatching/coturn/security/code-scanning/179)
the variable is confirmed to not be null in an outer loop guard
also changed the name of the variable in `rtcp_map_put`'s function declaration to match that used in its function definition
=> removed unnecessary null check

src/apps/uclient/startuclient.c
@ggarber i noticed too late that i used `0x03` instead of `0x02` by mistake - this is an issue because it means that `add_requested_family` will never be set when ipv6 is being used, so this should be fixed
=> typo correction

.github/workflows/cifuzz.yml, README.md
allow fuzzing to be performed as part of the continuous integration.
the timing of the fuzzing can be extended, and i aim to broaden the scope of the fuzz testing as well, since we currently only test the stun message parser.
=> add fuzzing to ci workflows

src/client/ns_turn_msg_defs.h, src/client/ns_turn_msg_defs_experimental.h
Source https://datatracker.ietf.org/doc/html/rfc8656#section-18
Now conforms to RFC specification
- ADDITIONAL_ADDRESS_FAMILY (0x8000) - was (0x8032)
- ADDRESS_ERROR_CODE (0x8001) - was (0x8033)
Fixes #1740
=> Update attribute values according to RFC 8656

src/apps/common/apputils.c, src/apps/relay/dbdrivers/dbd_mongo.c, src/apps/relay/http_server.c, src/apps/relay/netengine.c, src/apps/relay/ns_ioalib_engine_impl.c, src/apps/relay/turn_admin_server.c, src/apps/relay/userdb.c, src/apps/uclient/startuclient.c, src/apps/uclient/uclient.c, src/client/ns_turn_msg.c, src/server/ns_turn_maps.c
this pr aims to address more static code analyser warnings, specifically null pointer dereferences. the majority of changes are solely to quieten the analyser, as `malloc` and `calloc` are unlikely to fail, but this should at least lead to the code analysis being more readable and usable.
where functions addressed had existing failure strategies, they were used, however some functions will now silently fail rather than attempting to dereference a null pointer. if there is a preferred solution in these cases, i will be happy to implement it.
---
this is an extension of [this pull request](https://github.com/coturn/coturn/pull/1729)
=> address possible null pointer dereferences
